from airflow import Asset


CORE_CAPTION_UPDATED = Asset('CORE_CAPTION_UPDATED')
CORE_METADATA_UPDATED = Asset('CORE_METADATA_UPDATED')
CORE_TREE_DIFF_FOUND = Asset('CORE_TREE_DIFF_FOUND')
CORE_TREE_UPDATED = Asset('CORE_TREE_UPDATED')
